export interface DropZone {
  id: string;
  label?: string; // Add label for builder UI
  x: number; // Percentage from left
  y: number; // Percentage from top
  width: number; // Percentage width
  height: number; // Percentage height
  rotateX?: number; // 3D Perspective Rotation
  rotateY?: number; // 3D Perspective Rotation
  rotateZ?: number; // 2D flat rotation
  quadPoints?: [number, number, number, number, number, number, number, number]; // [tl_x, tl_y, tr_x, tr_y, br_x, br_y, bl_x, bl_y] as percents relative to zone rect
  itemScale?: number;
  itemOffsetX?: number;
  itemOffsetY?: number;
  zIndex?: number;
  acceptedItemIds: string[];
  silhouetteUrl?: string;
  successAudioUrl?: string; // Audio to play when correct item is dropped here
}

export interface DraggableItem {
  id: string;
  imageUrl: string;
  aiPrompt?: string; // Generated by AI Architect for image synthesis
  group?: string | null; // For categorization
  startX: number; // Percentage from left
  startY: number; // Percentage from top
  width: number; // Percentage width
  zIndex?: number;
  label?: string;
}

export interface ExerciseConfig {
  id: string;
  title: string;
  instructionAudioUrl?: string;
  backgroundImageUrl?: string;
  backgroundPrompt?: string; // Generated by AI Architect
  dropZones: DropZone[];
  items: DraggableItem[];
}
